---@type table<string, Vehicle>
return {
    -- ============================================
    -- STARTER VEHICLES ($15,000 - $25,000)
    -- Economy/used vehicles for new players
    -- ============================================

    -- Compacts ($15,000 - $18,000)
    asea = {
        name = 'Asea',
        brand = 'Declasse',
        model = 'asea',
        price = 15000,
        category = 'compacts',
        type = 'automobile',
        hash = `asea`,
    },
    blista = {
        name = 'Blista',
        brand = 'Dinka',
        model = 'blista',
        price = 16000,
        category = 'compacts',
        type = 'automobile',
        hash = `blista`,
    },
    rhapsody = {
        name = 'Rhapsody',
        brand = 'Declasse',
        model = 'rhapsody',
        price = 15500,
        category = 'compacts',
        type = 'automobile',
        hash = `rhapsody`,
    },
    issi2 = {
        name = 'Issi',
        brand = 'Weeny',
        model = 'issi2',
        price = 18000,
        category = 'compacts',
        type = 'automobile',
        hash = `issi2`,
    },
    panto = {
        name = 'Panto',
        brand = 'Benefactor',
        model = 'panto',
        price = 14000,
        category = 'compacts',
        type = 'automobile',
        hash = `panto`,
    },

    -- Sedans ($18,000 - $22,000)
    stanier = {
        name = 'Stanier',
        brand = 'Vapid',
        model = 'stanier',
        price = 18000,
        category = 'sedans',
        type = 'automobile',
        hash = `stanier`,
    },
    premier = {
        name = 'Premier',
        brand = 'Declasse',
        model = 'premier',
        price = 19000,
        category = 'sedans',
        type = 'automobile',
        hash = `premier`,
    },
    ingot = {
        name = 'Ingot',
        brand = 'Vulcar',
        model = 'ingot',
        price = 17500,
        category = 'sedans',
        type = 'automobile',
        hash = `ingot`,
    },
    intruder = {
        name = 'Intruder',
        brand = 'Karin',
        model = 'intruder',
        price = 20000,
        category = 'sedans',
        type = 'automobile',
        hash = `intruder`,
    },
    stratum = {
        name = 'Stratum',
        brand = 'Zirconium',
        model = 'stratum',
        price = 21000,
        category = 'sedans',
        type = 'automobile',
        hash = `stratum`,
    },

    -- Coupes ($20,000 - $25,000)
    previon = {
        name = 'Previon',
        brand = 'Karin',
        model = 'previon',
        price = 22000,
        category = 'coupes',
        type = 'automobile',
        hash = `previon`,
    },
    futo = {
        name = 'Futo',
        brand = 'Karin',
        model = 'futo',
        price = 23000,
        category = 'sports',
        type = 'automobile',
        hash = `futo`,
    },
    blista2 = {
        name = 'Blista Compact',
        brand = 'Dinka',
        model = 'blista2',
        price = 21000,
        category = 'sports',
        type = 'automobile',
        hash = `blista2`,
    },

    -- Starter Muscle ($22,000 - $25,000)
    picador = {
        name = 'Picador',
        brand = 'Cheval',
        model = 'picador',
        price = 24000,
        category = 'muscle',
        type = 'automobile',
        hash = `picador`,
    },
    buccaneer = {
        name = 'Buccaneer',
        brand = 'Albany',
        model = 'buccaneer',
        price = 25000,
        category = 'muscle',
        type = 'automobile',
        hash = `buccaneer`,
    },
    vigero = {
        name = 'Vigero',
        brand = 'Declasse',
        model = 'vigero',
        price = 25000,
        category = 'muscle',
        type = 'automobile',
        hash = `vigero`,
    },

    -- Starter Bikes ($8,000 - $18,000)
    faggio = {
        name = 'Faggio',
        brand = 'Pegassi',
        model = 'faggio',
        price = 8000,
        category = 'motorcycles',
        type = 'bike',
        hash = `faggio`,
    },
    faggio2 = {
        name = 'Faggio Sport',
        brand = 'Pegassi',
        model = 'faggio2',
        price = 12000,
        category = 'motorcycles',
        type = 'bike',
        hash = `faggio2`,
    },
    sanchez = {
        name = 'Sanchez',
        brand = 'Maibatsu',
        model = 'sanchez',
        price = 15000,
        category = 'motorcycles',
        type = 'bike',
        hash = `sanchez`,
    },
    pcj = {
        name = 'PCJ-600',
        brand = 'Shitzu',
        model = 'pcj',
        price = 18000,
        category = 'motorcycles',
        type = 'bike',
        hash = `pcj`,
    },

    -- Starter SUV/Utility ($20,000 - $25,000)
    rebel = {
        name = 'Rebel',
        brand = 'Karin',
        model = 'rebel',
        price = 22000,
        category = 'offroad',
        type = 'automobile',
        hash = `rebel`,
    },
    bodhi2 = {
        name = 'Bodhi',
        brand = 'Canis',
        model = 'bodhi2',
        price = 20000,
        category = 'offroad',
        type = 'automobile',
        hash = `bodhi2`,
    },

    -- ============================================
    -- ADDON VEHICLES
    -- ============================================

    -- Addon Vehicles [raz3r]
    a110 = {
        name = 'Alpine A110',
        brand = 'Alpine',
        model = 'a110',
        price = 85000,
        category = 'sports',
        type = 'automobile',
        hash = `a110`,
    },
    ['10chalrt'] = {
        name = '2010 Challenger RT',
        brand = 'Dodge',
        model = '10chalrt',
        price = 55000,
        category = 'muscle',
        type = 'automobile',
        hash = `10chalrt`,
    },
    ['19must'] = {
        name = '2019 Mustang',
        brand = 'Ford',
        model = '19must',
        price = 65000,
        category = 'muscle',
        type = 'automobile',
        hash = `19must`,
    },
    ['19roverv2'] = {
        name = '2019 Range Rover',
        brand = 'Land Rover',
        model = '19roverv2',
        price = 95000,
        category = 'suvs',
        type = 'automobile',
        hash = `19roverv2`,
    },
    ['22ct4v'] = {
        name = '2022 Cadillac CT4-V',
        brand = 'Cadillac',
        model = '22ct4v',
        price = 75000,
        category = 'sports',
        type = 'automobile',
        hash = `22ct4v`,
    },
    ['22f450'] = {
        name = '2022 Ford F-450',
        brand = 'Ford',
        model = '22f450',
        price = 85000,
        category = 'suvs',
        type = 'automobile',
        hash = `22f450`,
    },
    ['23camss'] = {
        name = '2023 Camaro SS',
        brand = 'Chevrolet',
        model = '23camss',
        price = 70000,
        category = 'sports',
        type = 'automobile',
        hash = `23camss`,
    },
    ['23tahoez71'] = {
        name = '2023 Tahoe Z71',
        brand = 'Chevrolet',
        model = '23tahoez71',
        price = 80000,
        category = 'suvs',
        type = 'automobile',
        hash = `23tahoez71`,
    },
    bmix = {
        name = 'BMW MIX',
        brand = 'BMW',
        model = 'bmix',
        price = 90000,
        category = 'sports',
        type = 'automobile',
        hash = `bmix`,
    },
    chevrst = {
        name = 'Chevrolet RST',
        brand = 'Chevrolet',
        model = 'chevrst',
        price = 60000,
        category = 'muscle',
        type = 'automobile',
        hash = `chevrst`,
    },
    evoxgsr = {
        name = 'Evo X GSR',
        brand = 'Mitsubishi',
        model = 'evoxgsr',
        price = 55000,
        category = 'sports',
        type = 'automobile',
        hash = `evoxgsr`,
    },
    ramclassic = {
        name = 'Ram Classic',
        brand = 'Dodge',
        model = 'ramclassic',
        price = 50000,
        category = 'offroad',
        type = 'automobile',
        hash = `ramclassic`,
    },
    -- Addon Vehicles [jon]
    dbfdsub = {
        name = 'Suburban',
        brand = 'Chevrolet',
        model = 'dbfdsub',
        price = 75000,
        category = 'emergency',
        type = 'automobile',
        hash = `dbfdsub`,
    },
    -- Addon Vehicles [Kane] - Motorcycles
    ['EZ-SoftBob'] = {
        name = 'EZ SoftBob',
        brand = 'Western',
        model = 'EZ-SoftBob',
        price = 45000,
        category = 'motorcycles',
        type = 'bike',
        hash = `EZ-SoftBob`,
    },
    ['EZ-Trike'] = {
        name = 'EZ Trike',
        brand = 'Western',
        model = 'EZ-Trike',
        price = 50000,
        category = 'motorcycles',
        type = 'bike',
        hash = `EZ-Trike`,
    },
    dirtyharry = {
        name = 'Dirty Harry',
        brand = 'Oscuro Customs',
        model = 'dirtyharry',
        price = 55000,
        category = 'motorcycles',
        type = 'bike',
        hash = `dirtyharry`,
    },
    softfxr24 = {
        name = 'softfxr24',
        brand = 'softfxr24',
        model = 'softfxr24',
        price = 50000,
        category = 'motorcycles',
        type = 'bike',
        hash = `darylj`,
    },
    theoutlaw = {
        name = 'The Outlaw',
        brand = 'Custom',
        model = 'theoutlaw',
        price = 55000,
        category = 'motorcycles',
        type = 'bike',
        hash = `theoutlaw`,
    },
    glider3 = {
        name = 'Glider 3',
        brand = 'Custom',
        model = 'glider3',
        price = 50000,
        category = 'motorcycles',
        type = 'bike',
        hash = `glider3`,
    },
    inkknuck = {
        name = 'Ink Knuckle',
        brand = 'Custom',
        model = 'inkknuck',
        price = 48000,
        category = 'motorcycles',
        type = 'bike',
        hash = `inkknuck`,
    },
    ['inkshoverturbo'] = {
        name = 'Ink Shover Turbo',
        brand = 'Custom',
        model = 'inkshoverturbo',
        price = 55000,
        category = 'motorcycles',
        type = 'bike',
        hash = `inkshoverturbo`,

    },
    kingrod21 = {
        name = 'King Rod 21',
        brand = 'Custom',
        model = 'kingrod21',
        price = 53000,
        category = 'motorcycles',
        type = 'bike',
        hash = `kingrod21`,
    },
    opie = {
        name = 'Opie',
        brand = 'Custom',
        model = 'opie',
        price = 48000,
        category = 'motorcycles',
        type = 'bike',
        hash = `opie`,
    },
    oscpan24 = {
        name = 'Osc Pan 24',
        brand = 'Custom',
        model = 'oscpan24',
        price = 52000,
        category = 'motorcycles',
        type = 'bike',
        hash = `oscpan24`,
    },
    panchop1 = {
        name = 'Pan Chop 1',
        brand = 'Custom',
        model = 'panchop1',
        price = 50000,
        category = 'motorcycles',
        type = 'bike',
        hash = `panchop1`,
    },
    performancechop = {
        name = 'Performance Chop',
        brand = 'Custom',
        model = 'performancechop',
        price = 55000,
        category = 'motorcycles',
        type = 'bike',
        hash = `performancechop`,
    },
    sportsterchop = {
        name = 'Sportster Chop',
        brand = 'Custom',
        model = 'sportsterchop',
        price = 48000,
        category = 'motorcycles',
        type = 'bike',
        hash = `sportsterchop`,
    },
    clubrg = {
        name = 'Club Road Glide',
        brand = 'Custom',
        model = 'clubrg',
        price = 60000,
        category = 'motorcycles',
        type = 'bike',
        hash = `clubrg`,
    },
    customrg224 = {
        name = 'Custom Road Glide 224',
        brand = 'Custom',
        model = 'customrg224',
        price = 65000,
        category = 'motorcycles',
        type = 'bike',
        hash = `customrg224`,
    },
    ['42knucklehead'] = {
        name = '42 Knucklehead',
        brand = 'Custom',
        model = '42knucklehead',
        price = 70000,
        category = 'motorcycles',
        type = 'bike',
        hash = `42knucklehead`,
    },
    bloodlinesg24 = {
        name = 'Bloodlines G24',
        brand = 'Custom',
        model = 'bloodlinesg24',
        price = 60000,
        category = 'motorcycles',
        type = 'bike',
        hash = `bloodlinesg24`,
    },
    saintscholo = {
        name = 'Saints Cholo',
        brand = 'Custom',
        model = 'saintscholo',
        price = 55000,
        category = 'motorcycles',
        type = 'bike',
        hash = `saintscholo`,
    },
    Shredder = {
        name = 'Shredder',
        brand = 'Custom',
        model = 'Shredder',
        price = 60000,
        category = 'motorcycles',
        type = 'bike',
        hash = `Shredder`,
    },
    silver67 = {
        name = 'Silver 67',
        brand = 'Custom',
        model = 'silver67',
        price = 65000,
        category = 'sedans',
        type = 'automobile',
        hash = `silver67`,
    },
    rgcvost24 = {
        name = 'RGC Vost 24',
        brand = 'Custom',
        model = 'rgcvost24',
        price = 60000,
        category = 'motorcycles',
        type = 'bike',
        hash = `rgcvost24`,
    },
    kingcholov3 = {
        name = 'King Cholo V3',
        brand = 'Custom',
        model = 'kingcholov3',
        price = 58000,
        category = 'motorcycles',
        type = 'bike',
        hash = `kingcholov3`,
    },
    lincont62 = {
        name = 'Lincoln Cont 62',
        brand = 'Custom',
        model = 'lincont62',
        price = 70000,
        category = 'sedans',
        type = 'automobile',
        hash = `lincont62`,
    },
    lowriderst820 = {
        name = 'Lowrider ST 820',
        brand = 'Custom',
        model = 'lowriderst820',
        price = 55000,
        category = 'motorcycles',
        type = 'bike',
        hash = `lowriderst820`,
    },
    lowpan64 = {
        name = 'Low Pan 64',
        brand = 'Custom',
        model = 'lowpan64',
        price = 50000,
        category = 'motorcycles',
        type = 'bike',
        hash = `lowpan64`,
    },
    ['drunkenvikingchop'] = {
        name = 'Drunken Viking Chop',
        brand = 'Custom',
        model = 'drunkenvikingchop',
        price = 55000,
        category = 'motorcycles',
        type = 'bike',
        hash = `drunkenvikingchop`,
    },
    hycsun = {
        name = 'HYC Sunrise',
        brand = 'Custom',
        model = 'hycsun',
        price = 60000,
        category = 'sedan',
        type = 'automobile',
        hash = 'hycsun',
    },
    -- Addon Vehicles [Kane] - Cars
    vulture = {
        name = 'Vulture',
        brand = 'Custom',
        model = 'vulture',
        price = 120000,
        category = 'muscle',
        type = 'automobile',
        hash = `vulture`,
    },
    gauntletstx = {
        name = 'Gauntlet STX',
        brand = 'Bravado',
        model = 'gauntletstx',
        price = 95000,
        category = 'muscle',
        type = 'automobile',
        hash = `gauntletstx`,
    },
    gresleyh = {
        name = 'Gresley H',
        brand = 'Declasse',
        model = 'gresleyh',
        price = 85000,
        category = 'suvs',
        type = 'automobile',
        hash = `gresleyh`,
    },
    mrapbb = {
        name = 'MRAP BB',
        brand = 'Military',
        model = 'mrapbb',
        price = 200000,
        category = 'offroad',
        type = 'automobile',
        hash = `mrapbb`,
    },
    ['jd23tahoeamber'] = {
        name = '2023 Tahoe Amber',
        brand = 'Chevrolet',
        model = 'jd23tahoeamber',
        price = 85000,
        category = 'suvs',
        type = 'automobile',
        hash = `jd23tahoeamber`,
    },
    Mansoryphantom8 = {
        name = 'Mansory Phantom 8',
        brand = 'Rolls-Royce',
        model = 'Mansoryphantom8',
        price = 500000,
        category = 'sedans',
        type = 'automobile',
        hash = `Mansoryphantom8`,
    },
    roxanne = {
        name = 'Roxanne',
        brand = 'Custom',
        model = 'roxanne',
        price = 150000,
        category = 'super',
        type = 'automobile',
        hash = `roxanne`,
    },
    sprinter = {
        name = 'Sprinter',
        brand = 'western',
        model = 'sprinter',
        price = 65000,
        category = 'motorcycle',
        type = 'motorcycle',
        hash = `sprinter`,
    },
    -- Base Game Vehicles
    defiler = {
        name = 'Defiler',
        brand = 'Shitzu',
        model = 'defiler',
        price = 42500,
        category = 'motorcycles',
        type = 'bike',
        hash = `defiler`,
    },
    enduro = {
        name = 'Enduro',
        brand = 'Dinka',
        model = 'enduro',
        price = 38000,
        category = 'motorcycles',
        type = 'bike',
        hash = `enduro`,
    },
    ['EZ-GangVanv2'] = {
        name = 'EZ Gang Van V2',
        brand = 'Custom',
        model = 'EZ-GangVanv2',
        price = 55000,
        category = 'vans',
        type = 'automobile',
        hash = `EZ-GangVanv2`,
    },
    type258 = {
        name = 'Type 258',
        brand = 'Custom',
        model = 'type258',
        price = 45000,
        category = 'vans',
        type = 'automobile',
        hash = `type258`,
    },
    imperial = {
        name = 'Imperial',
        brand = 'Custom',
        model = 'imperial',
        price = 80000,
        category = 'sedans',
        type = 'automobile',
        hash = `imperial`,
    },
    nspeedo = {
        name = 'Speedo Express',
        brand = 'Vapid',
        model = 'nspeedo',
        price = 40000,
        category = 'vans',
        type = 'automobile',
        hash = `nspeedo`,
    },
    -- Job Vehicles
    bus = {
        name = 'Bus',
        brand = 'Public Transport',
        model = 'bus',
        price = 0,
        category = 'commercial',
        type = 'automobile',
        hash = `bus`,
    },
    taxi = {
        name = 'Taxi',
        brand = 'Taxi',
        model = 'taxi',
        price = 0,
        category = 'sedans',
        type = 'automobile',
        hash = `taxi`,
    },
    trash2 = {
        name = 'Garbage Truck',
        brand = 'Waste Management',
        model = 'trash2',
        price = 0,
        category = 'industrial',
        type = 'automobile',
        hash = `trash2`,
    },
    towtruck = {
        name = 'Tow Truck',
        brand = 'Mechanic',
        model = 'towtruck',
        price = 0,
        category = 'industrial',
        type = 'automobile',
        hash = `towtruck`,
    },
    stockade = {
        name = 'Stockade',
        brand = 'Security',
        model = 'stockade',
        price = 0,
        category = 'commercial',
        type = 'automobile',
        hash = `stockade`,
    },
    -- Police Vehicles (from resources/[vehicles]/[police])
    ['23camslick'] = {
        name = '23camslick',
        brand = 'Custom',
        model = '23camslick',
        price = 0,
        category = 'teu',
        type = 'automobile',
        hash = `23camslick`,
    },
    ['24mustslick'] = {
        name = '24mustslick',
        brand = 'Custom',
        model = '24mustslick',
        price = 0,
        category = 'teu',
        type = 'automobile',
        hash = `24mustslick`,
    },
    c3outlaw = {
        name = 'c3outlaw',
        brand = 'Custom',
        model = 'c3outlaw',
        price = 0,
        category = 'teu',
        type = 'automobile',
        hash = `c3outlaw`,
    },
    dbjd25f150stx = {
        name = 'Ford F-150 STX',
        brand = 'Ford',
        model = 'dbjd25f150stx',
        price = 0,
        category = 'police',
        type = 'automobile',
        hash = `dbjd25f150stx`,
    },
    dbjdhard23tahoe = {
        name = '2023 Tahoe',
        brand = 'Chevrolet',
        model = 'dbjdhard23tahoe',
        price = 0,
        category = 'police',
        type = 'automobile',
        hash = `dbjdhard23tahoe`,
    },
    jddbepd15fpiu = {
        name = '2015 FPIU',
        brand = 'Ford',
        model = 'jddbepd15fpiu',
        price = 0,
        category = 'police',
        type = 'automobile',
        hash = `jddbepd15fpiu`,
    },
    jddbhard23tahoebb = {
        name = '2023 Tahoe BB',
        brand = 'Chevrolet',
        model = 'jddbhard23tahoebb',
        price = 0,
        category = 'police',
        type = 'automobile',
        hash = `jddbhard23tahoebb`,
    },
    jw_pursuitdemon = {
        name = 'jw_pursuitdemon',
        brand = 'Custom',
        model = 'jw_pursuitdemon',
        price = 0,
        category = 'teu',
        type = 'automobile',
        hash = `jw_pursuitdemon`,
    },
    jw_pursuitdemonslick = {
        name = 'jw_pursuitdemonslick',
        brand = 'Custom',
        model = 'jw_pursuitdemonslick',
        price = 0,
        category = 'teu',
        type = 'automobile',
        hash = `jw_pursuitdemonslick`,
    },
    jw_supersnakeslick = {
        name = 'jw_supersnakeslick',
        brand = 'Custom',
        model = 'jw_supersnakeslick',
        price = 0,
        category = 'teu',
        type = 'automobile',
        hash = `jw_supersnakeslick`,
    },
    nypd22mach = {
        name = 'nypd22mach',
        brand = 'Custom',
        model = 'nypd22mach',
        price = 0,
        category = 'teu',
        type = 'automobile',
        hash = `nypd22mach`,
    },
    ucdura = {
        name = 'Durango',
        brand = 'Dodge',
        model = 'ucdura',
        price = 0,
        category = 'police',
        type = 'automobile',
        hash = `ucdura`,
    },
    -- JaDesigns Police Vehicles (Valor Lightbar)
    fedsig08char = {
        name = '2008 Charger Valor',
        brand = 'Dodge',
        model = 'fedsig08char',
        price = 15000,
        category = 'police',
        type = 'automobile',
        hash = `fedsig08char`,
    },
    fedsig13taurus = {
        name = '2013 Taurus Valor',
        brand = 'Ford',
        model = 'fedsig13taurus',
        price = 15000,
        category = 'police',
        type = 'automobile',
        hash = `fedsig13taurus`,
    },
    fedsig14char = {
        name = '2014 Charger Valor',
        brand = 'Dodge',
        model = 'fedsig14char',
        price = 15000,
        category = 'police',
        type = 'automobile',
        hash = `fedsig14char`,
    },
    fedsig18char = {
        name = '2018 Charger Valor',
        brand = 'Dodge',
        model = 'fedsig18char',
        price = 15000,
        category = 'police',
        type = 'automobile',
        hash = `fedsig18char`,
    },
    fedsig18tahoe = {
        name = '2018 Tahoe Valor',
        brand = 'Chevrolet',
        model = 'fedsig18tahoe',
        price = 15000,
        category = 'police',
        type = 'automobile',
        hash = `fedsig18tahoe`,
    },
    fedsig20fpiu = {
        name = '2020 FPIU Valor',
        brand = 'Ford',
        model = 'fedsig20fpiu',
        price = 15000,
        category = 'police',
        type = 'automobile',
        hash = `fedsig20fpiu`,
    },
    fedsig21durango = {
        name = '2021 Durango Valor',
        brand = 'Dodge',
        model = 'fedsig21durango',
        price = 15000,
        category = 'police',
        type = 'automobile',
        hash = `fedsig21durango`,
    },
    newvic = {
        name = 'Crown Victoria Valor',
        brand = 'Ford',
        model = 'newvic',
        price = 15000,
        category = 'police',
        type = 'automobile',
        hash = `newvic`,
    },
    -- EMS Vehicles
    c325ambo = {
        name = 'C325 Ambulance',
        brand = 'Chevrolet',
        model = 'c325ambo',
        price = 0,
        category = 'EMS',
        type = 'automobile',
        hash = `c325ambo`,
    },
    ems20fpiu = {
        name = 'EMS 2020 FPIU',
        brand = 'Ford',
        model = 'ems20fpiu',
        price = 0,
        category = 'EMS',
        type = 'automobile',
        hash = `ems20fpiu`,
    },
    m2ccmed = {
        name = 'M2CC Medical',
        brand = 'Freightliner',
        model = 'm2ccmed',
        price = 0,
        category = 'EMS',
        type = 'automobile',
        hash = `m2ccmed`,
    },
    ram3500hrr = {
        name = 'Ram 3500 HRR',
        brand = 'Dodge',
        model = 'ram3500hrr',
        price = 0,
        category = 'EMS',
        type = 'automobile',
        hash = `ram3500hrr`,
    },
    -- Emergency Aircraft
    ['909_seahawk'] = {
        name = 'MH-60 Seahawk',
        brand = 'Sikorsky',
        model = '909_seahawk',
        price = 0,
        category = 'esair',
        type = 'heli',
        hash = `909_seahawk`,
    },
    as365 = {
        name = 'AS365 Dauphin',
        brand = 'Airbus',
        model = 'as365',
        price = 0,
        category = 'esair',
        type = 'heli',
        hash = `as365`,
    },
    c3aw139 = {
        name = 'AW139',
        brand = 'Leonardo',
        model = 'c3aw139',
        price = 0,
        category = 'esair',
        type = 'heli',
        hash = `c3aw139`,
    },
    c3swathawk = {
        name = 'SWAT Hawk',
        brand = 'Sikorsky',
        model = 'c3swathawk',
        price = 0,
        category = 'esair',
        type = 'heli',
        hash = `c3swathawk`,
    },
    ec145med = {
        name = 'EC145 Medical',
        brand = 'Airbus',
        model = 'ec145med',
        price = 0,
        category = 'esair',
        type = 'heli',
        hash = `ec145med`,
    },
    swat145c = {
        name = 'SWAT EC145',
        brand = 'Airbus',
        model = 'swat145c',
        price = 0,
        category = 'esair',
        type = 'heli',
        hash = `swat145c`,
    },
    swatec135 = {
        name = 'SWAT EC135',
        brand = 'Airbus',
        model = 'swatec135',
        price = 0,
        category = 'esair',
        type = 'heli',
        hash = `swatec135`,
    },
} 