["largemouthbass"] = {
    label = "Largemouth Bass",
    weight = 3000,
    stack = true,
    close = true,
    description = "Fish for Fishing.",
    client = {
        image = "largemouthbass.png",
    },
    name = "largemouthbass",
    type = "item",
    image = "largemouthbass.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["item_bench"] = {
    label = "Workbench",
    weight = 15000,
    stack = false,
    close = true,
    description = "A workbench to craft items.",
    client = {
        image = "item_bench.png",
    },
    name = "item_bench",
    type = "item",
    image = "item_bench.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["fishingnet"] = {
    label = "Fish Net",
    weight = 5000,
    stack = false,
    close = true,
    description = "A net used for catching fish!",
    client = {
        image = "fishingnet.png",
    },
    name = "fishingnet",
    type = "item",
    image = "fishingnet.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["emerald"] = {
    label = "Emerald",
    weight = 3000,
    stack = true,
    close = true,
    description = "Emerald",
    client = {
        image = "emerald.png",
    },
    name = "emerald",
    type = "item",
    image = "emerald.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["chestkey"] = {
    label = "Key",
    weight = 1000,
    stack = true,
    close = true,
    description = "A gold key.",
    client = {
        image = "chestkey.png",
    },
    name = "chestkey",
    type = "item",
    image = "chestkey.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["rainbowtrout"] = {
    label = "Rainbowtrout",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for rainbowtrout",
    client = {
        image = "rainbowtrout.png",
    },
    name = "rainbowtrout",
    type = "item",
    image = "rainbowtrout.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["stripedbass"] = {
    label = "Stripedbass",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for stripedbass",
    client = {
        image = "stripedbass.png",
    },
    name = "stripedbass",
    type = "item",
    image = "stripedbass.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["catfish"] = {
    label = "Catfish",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for catfish",
    client = {
        image = "catfish.png",
    },
    name = "catfish",
    type = "item",
    image = "catfish.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["swordfish"] = {
    label = "Swordfish",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for swordfish",
    client = {
        image = "swordfish.png",
    },
    name = "swordfish",
    type = "item",
    image = "swordfish.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["cookedfish"] = {
    label = "Cookedfish",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for cookedfish",
    client = {
        image = "cookedfish.png",
    },
    name = "cookedfish",
    type = "item",
    image = "cookedfish.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["fishingrod3"] = {
    label = "Fishingrod3",
    weight = 1000,
    stack = false,
    close = true,
    description = "Description for fishingrod3",
    client = {
        image = "fishingrod3.png",
    },
    name = "fishingrod3",
    type = "item",
    image = "fishingrod3.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["fish"] = {
    label = "Fish",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for fish",
    client = {
        image = "fish.png",
    },
    name = "fish",
    type = "item",
    image = "fish.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["treasuremap"] = {
    label = "Treasuremap",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for treasuremap",
    client = {
        image = "treasuremap.png",
    },
    name = "treasuremap",
    type = "item",
    image = "treasuremap.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["ruby"] = {
    label = "Ruby",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for ruby",
    client = {
        image = "ruby.png",
    },
    name = "ruby",
    type = "item",
    image = "ruby.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["fishingbait"] = {
    label = "Fishingbait",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for fishingbait",
    client = {
        image = "fishingbait.png",
    },
    name = "fishingbait",
    type = "item",
    image = "fishingbait.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["treasurechest"] = {
    label = "Treasurechest",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for treasurechest",
    client = {
        image = "treasurechest.png",
    },
    name = "treasurechest",
    type = "item",
    image = "treasurechest.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["attachment_bench"] = {
    label = "Attachment bench",
    weight = 1000,
    stack = false,
    close = true,
    description = "Description for attachment_bench",
    client = {
        image = "attachment_bench.png",
    },
    name = "attachment_bench",
    type = "item",
    image = "attachment_bench.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["fishinglure"] = {
    label = "Fishinglure",
    weight = 1000,
    stack = false,
    close = true,
    description = "Description for fishinglure",
    client = {
        image = "fishinglure.png",
    },
    name = "fishinglure",
    type = "item",
    image = "fishinglure.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["perfectlycookedfish"] = {
    label = "Perfectlycookedfish",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for perfectlycookedfish",
    client = {
        image = "perfectlycookedfish.png",
    },
    name = "perfectlycookedfish",
    type = "item",
    image = "perfectlycookedfish.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["salmon"] = {
    label = "Salmon",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for salmon",
    client = {
        image = "salmon.png",
    },
    name = "salmon",
    type = "item",
    image = "salmon.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["tunafish"] = {
    label = "Tunafish",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for tunafish",
    client = {
        image = "tunafish.png",
    },
    name = "tunafish",
    type = "item",
    image = "tunafish.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["tigershark"] = {
    label = "Tigershark",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for tigershark",
    client = {
        image = "tigershark.png",
    },
    name = "tigershark",
    type = "item",
    image = "tigershark.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["fishinglure2"] = {
    label = "Fishinglure2",
    weight = 1000,
    stack = false,
    close = true,
    description = "Description for fishinglure2",
    client = {
        image = "fishinglure2.png",
    },
    name = "fishinglure2",
    type = "item",
    image = "fishinglure2.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["codfish"] = {
    label = "Codfish",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for codfish",
    client = {
        image = "codfish.png",
    },
    name = "codfish",
    type = "item",
    image = "codfish.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["eelfish"] = {
    label = "Eelfish",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for eelfish",
    client = {
        image = "eelfish.png",
    },
    name = "eelfish",
    type = "item",
    image = "eelfish.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["skillreel"] = {
    label = "Skillreel",
    weight = 1000,
    stack = false,
    close = true,
    description = "Description for skillreel",
    client = {
        image = "skillreel.png",
    },
    name = "skillreel",
    type = "item",
    image = "skillreel.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["fishingfireplace"] = {
    label = "Fishingfireplace",
    weight = 1000,
    stack = false,
    close = true,
    description = "Description for fishingfireplace",
    client = {
        image = "fishingfireplace.png",
    },
    name = "fishingfireplace",
    type = "item",
    image = "fishingfireplace.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["yellowdiamond"] = {
    label = "Yellowdiamond",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for yellowdiamond",
    client = {
        image = "yellowdiamond.png",
    },
    name = "yellowdiamond",
    type = "item",
    image = "yellowdiamond.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["fishingshovel"] = {
    label = "Fishingshovel",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for fishingshovel",
    client = {
        image = "fishingshovel.png",
    },
    name = "fishingshovel",
    type = "item",
    image = "fishingshovel.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["proreel"] = {
    label = "Proreel",
    weight = 1000,
    stack = false,
    close = true,
    description = "Description for proreel",
    client = {
        image = "proreel.png",
    },
    name = "proreel",
    type = "item",
    image = "proreel.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["goldfish"] = {
    label = "Goldfish",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for goldfish",
    client = {
        image = "goldfish.png",
    },
    name = "goldfish",
    type = "item",
    image = "goldfish.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["redfish"] = {
    label = "Redfish",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for redfish",
    client = {
        image = "redfish.png",
    },
    name = "redfish",
    type = "item",
    image = "redfish.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["captainskull"] = {
    label = "Captainskull",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for captainskull",
    client = {
        image = "captainskull.png",
    },
    name = "captainskull",
    type = "item",
    image = "captainskull.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["fishingrod2"] = {
    label = "Fishingrod2",
    weight = 1000,
    stack = false,
    close = true,
    description = "Description for fishingrod2",
    client = {
        image = "fishingrod2.png",
    },
    name = "fishingrod2",
    type = "item",
    image = "fishingrod2.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["killerwhale"] = {
    label = "Killerwhale",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for killerwhale",
    client = {
        image = "killerwhale.png",
    },
    name = "killerwhale",
    type = "item",
    image = "killerwhale.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["sapphire"] = {
    label = "Sapphire",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for sapphire",
    client = {
        image = "sapphire.png",
    },
    name = "sapphire",
    type = "item",
    image = "sapphire.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["bottlemap"] = {
    label = "Bottlemap",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for bottlemap",
    client = {
        image = "bottlemap.png",
    },
    name = "bottlemap",
    type = "item",
    image = "bottlemap.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["fishingtrowl"] = {
    label = "Fishingtrowl",
    weight = 1000,
    stack = false,
    close = true,
    description = "Description for fishingtrowl",
    client = {
        image = "fishingtrowl.png",
    },
    name = "fishingtrowl",
    type = "item",
    image = "fishingtrowl.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["gholfish"] = {
    label = "Gholfish",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for gholfish",
    client = {
        image = "gholfish.png",
    },
    name = "gholfish",
    type = "item",
    image = "gholfish.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["fishingrod"] = {
    label = "Fishingrod",
    weight = 1000,
    stack = false,
    close = true,
    description = "Description for fishingrod",
    client = {
        image = "fishingrod.png",
    },
    name = "fishingrod",
    type = "item",
    image = "fishingrod.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["stingraymeat"] = {
    label = "Stingraymeat",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for stingraymeat",
    client = {
        image = "stingraymeat.png",
    },
    name = "stingraymeat",
    type = "item",
    image = "stingraymeat.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["bluefish"] = {
    label = "Bluefish",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for bluefish",
    client = {
        image = "bluefish.png",
    },
    name = "bluefish",
    type = "item",
    image = "bluefish.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["fishinganchor"] = {
    label = "Fishinganchor",
    weight = 1000,
    stack = false,
    close = true,
    description = "Description for fishinganchor",
    client = {
        image = "fishinganchor.png",
    },
    name = "fishinganchor",
    type = "item",
    image = "fishinganchor.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["sockeyesalmon"] = {
    label = "Sockeyesalmon",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for sockeyesalmon",
    client = {
        image = "sockeyesalmon.png",
    },
    name = "sockeyesalmon",
    type = "item",
    image = "sockeyesalmon.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["rockfish"] = {
    label = "Rockfish",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for rockfish",
    client = {
        image = "rockfish.png",
    },
    name = "rockfish",
    type = "item",
    image = "rockfish.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["flyfish"] = {
    label = "Flyfish",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for flyfish",
    client = {
        image = "flyfish.png",
    },
    name = "flyfish",
    type = "item",
    image = "flyfish.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["tarponfish"] = {
    label = "Tarponfish",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for tarponfish",
    client = {
        image = "tarponfish.png",
    },
    name = "tarponfish",
    type = "item",
    image = "tarponfish.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["fishinghalibut"] = {
    label = "Fishinghalibut",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for fishinghalibut",
    client = {
        image = "fishinghalibut.png",
    },
    name = "fishinghalibut",
    type = "item",
    image = "fishinghalibut.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["anglerfish"] = {
    label = "Anglerfish",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for anglerfish",
    client = {
        image = "anglerfish.png",
    },
    name = "anglerfish",
    type = "item",
    image = "anglerfish.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["kingsalmon"] = {
    label = "Kingsalmon",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for kingsalmon",
    client = {
        image = "kingsalmon.png",
    },
    name = "kingsalmon",
    type = "item",
    image = "kingsalmon.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["mahimahi"] = {
    label = "Mahimahi",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for mahimahi",
    client = {
        image = "mahimahi.png",
    },
    name = "mahimahi",
    type = "item",
    image = "mahimahi.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["crawfish"] = {
    label = "Crawfish",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for crawfish",
    client = {
        image = "crawfish.png",
    },
    name = "crawfish",
    type = "item",
    image = "crawfish.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["oceansturgeon"] = {
    label = "Oceansturgeon",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for oceansturgeon",
    client = {
        image = "oceansturgeon.png",
    },
    name = "oceansturgeon",
    type = "item",
    image = "oceansturgeon.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["fishinglog"] = {
    label = "Fishinglog",
    weight = 1000,
    stack = false,
    close = true,
    description = "Description for fishinglog",
    client = {
        image = "fishinglog.png",
    },
    name = "fishinglog",
    type = "item",
    image = "fishinglog.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["fishingcrabtrap"] = {
    label = "Fishingcrabtrap",
    weight = 1000,
    stack = false,
    close = true,
    description = "Description for fishingcrabtrap",
    client = {
        image = "fishingcrabtrap.png",
    },
    name = "fishingcrabtrap",
    type = "item",
    image = "fishingcrabtrap.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["bluecrab"] = {
    label = "Bluecrab",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for bluecrab",
    client = {
        image = "bluecrab.png",
    },
    name = "bluecrab",
    type = "item",
    image = "bluecrab.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["dungenesscrab"] = {
    label = "Dungenesscrab",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for dungenesscrab",
    client = {
        image = "dungenesscrab.png",
    },
    name = "dungenesscrab",
    type = "item",
    image = "dungenesscrab.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["rockcrab"] = {
    label = "Rockcrab",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for rockcrab",
    client = {
        image = "rockcrab.png",
    },
    name = "rockcrab",
    type = "item",
    image = "rockcrab.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["redcrab"] = {
    label = "Redcrab",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for redcrab",
    client = {
        image = "redcrab.png",
    },
    name = "redcrab",
    type = "item",
    image = "redcrab.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["snowcrab"] = {
    label = "Snowcrab",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for snowcrab",
    client = {
        image = "snowcrab.png",
    },
    name = "snowcrab",
    type = "item",
    image = "snowcrab.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
["cookedcrab"] = {
    label = "Cookedcrab",
    weight = 1000,
    stack = true,
    close = true,
    description = "Description for cookedcrab",
    client = {
        image = "cookedcrab.png",
    },
    name = "cookedcrab",
    type = "item",
    image = "cookedcrab.png",
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
},
